Api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .swagger_schema import swagger
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Hostel API')


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'hostel', views.HostelViewSet)
router.register(r'login', views.LoginView, basename='MyModel')
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include(router.urls), name='rest-api'),
    # path('openapi/', TemplateView.as_view(
    #     template_name='CRUD/swagger-ui.html',
    #     extra_context={'schema_url': 'openapi-schema'}
    # ), name='swagger-ui'),
    # path('openapi/', schema_view, name='open-api'),
    path('swagger/', swagger),

    # path('example/', views.ExampleView.as_view()),
    # path('login/', obtain_auth_token, name='api-login'),


]

CRUD/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'CRUD'

urlpatterns = [

    #admin dashboard login,logout...vi
    path('search/', views.Search, name='search'),
    # path('search-user/', views.search, name='search-user'),
    path('map/', views.mapview, name='map'),
    path("login/", LoginView.as_view(), name ='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    #create ,upadte,list and delete single object
    path("main/", Hostel_CreateView.as_view(), name='add-hostel'),
    path('view/', Hostel_ListView.as_view(), name='list-hostel'),
    path('hostel-list/', Hostels.as_view(), name='hostel-list'),
    path('delete/<int:id>/', Hostel_DeleteView.as_view(), name='delete-single-hostel'),
    path('update/<int:id>/', Hostel_UpdateView.as_view(), name='update-hostel'),
    path('manageusers/', Users_ListView.as_view(), name='list-users'),
    
    #path("register/", RegisterView.as_view(),name="register"),
    #list hostel request,accept or delete request
    path('hostel-request-list/', Hostel_Request_ListView.as_view(), name='list-req-hostel'),
    path('hostel-accept/<int:pk>/', Hostel_AcceptView.accept, name='hostel-accept'),
    path('hostel-reject/<int:pk>/', Hostel_RejectView.reject, name='hostel-reject'),
    path('hostel-request-view/<int:pk>', views.hostel_DetailView, name='hostel-request-view'),

    path('delete-hostel/', DeleteGroup.deleteHostel, name='delete-hostel'),
    path('delete-user/', DeleteGroup.deleteUser, name='delete-user'),
    #Client register,create,verify,login
    #path("client-login/", ClientLoginView.as_view()),
    path("register/", ClientRegisterView.as_view(),name="register"),
    path("activation-sent/",views.verifyNotification,name='activation-sent'),
    path("client/", Client_CreateView.as_view(), name='insert'),
    path ("client-map/",views.clientmap,name="client-map"),
    
    
    #url (r"^direction/(?P<h_long>[0-9]+)/$",views.direction,name="direction"),
    path ("direction/<str:h_long>/<str:h_lat>/",views.direction, name='direction'),
    
    path("comments/", Comments.as_view(), name='comments'),
    path("comment-form/<int:id>/",views.commentform,name='commentform'),
    path('delete-comment/', DeleteGroup.deleteComment, name='delete-comment'),
    path('delete-comment-all/', DeleteGroup.deleteCommentAll, name='delete-comment-all'),
    re_path('hostel-comments/', Hostel_Comments.get, name='hostel-comments'),

    #path("user-comment/", views.comment, name='user-comment'),
    
    #sort hostel
    path("cheap-hostel/", views.cheapSortHostel, name='cheap-hostel'),
    path("expen-hostel/", views.expenSortHostel, name='expen-hostel'),
    path("boys-hostel/",views.sortMale, name='boys-hostel'),
    path("girls-hostel/",views.sortFemale, name='girls-hostel'),

    url (r"^search-hostel/$",views.searchhostel),
    path ("hostel-detail/",views.totalhostel,name="total-hostel"),
    #account activaiton link
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    #nearest
    path ("nearest/<str:h_long>/<str:h_lat>/",views.nearest,name="nearest-hostel"),
    
    
]

hostel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from CRUD import views, models
from CRUD.admin import custom_admin_site
from django.views.generic import RedirectView
from rest_framework import routers

#
urlpatterns = [
    path('admin/', custom_admin_site.urls),
    # path('', views.index, name='index'),
    path("hostel/", include("CRUD.urls")),
    path("account/", include("accounts.urls")),
    # path('api-hostel/', views.Api_Hostel.as_view()),
    # path('api-comment/', views.Api_Comment.as_view()),
    # path('api-comment-crud/<int:id>', views.Api_Crud.as_view()),
    # path('api-hostel-add/', views.Api_Hostel_Add.as_view()),
    # path('api-image/', views.Api_Image.as_view()),
    path("", include("Api.urls"))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

CRUD/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from .models import Hostel_info,Hostel_Request,Request_Image,Image
from .forms import Hostel_Request_Form, Hostel_comment
from django.db.models import Q
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics, serializers
from .serializers import Hostel_infoSerializers, Hostel_commentSerializers,ImageSerializers

from django.contrib.auth.decorators import *
from django.contrib.admin.views.decorators import *
from CRUD.decorators import user_is_admin_required

from django.contrib.auth import get_user_model

from django.views.generic import ListView, DetailView, TemplateView, FormView, View, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .forms import *
from django.contrib.auth import authenticate, login, logout
#send mail
from django.core.mail import send_mail

#Encrypion,decryption,text byte and text
from django.conf import settings
from django.utils.encoding import force_bytes,force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from CRUD.token import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect

User = get_user_model()

def index(request):
    return render(request,"CRUD/index.html")

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/hostel/login/")


class LoginView(FormView):
    template_name = "CRUD/login.html"
    form_class = LoginForm
    redirect_field_name = "/hostel/client-map/" 
    success_url="/hostel/client-map/"          #-------sends to client if not admin

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        user = authenticate(email=email, password=pword)
        if user is not None:
            login(self.request, user)
            if user.is_admin:
                return redirect("/hostel/main/")
        else:
            return render(self.request, "CRUD/login.html", {"error": "Invalid Credential", "form": form})
        return super().form_valid(form)

class ClientLoginView(FormView):
    template_name = "CRUD/login.html"
    form_class = LoginForm
    success_url = "/hostel/client/"
    
    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        user = authenticate(email=email, password=pword)
        if user is not None:
            login(self.request, user)            
        else:
            return render(self.request, "CRUD/login.html", {"error": "Invalid Credential", "form": form})
        return super(ClientLoginView,self).form_valid(form)

      

class ClientRegisterView(FormView):
    template_name = "CRUD/RegistrationForm.html"
    form_class = SignupForm
    success_url = "/hostel/activation-sent/"

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        #send message and token for authentication
        subject = 'Thank you for registering to our site'    
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [email,]
        current_site = get_current_site(self.request).domain
        
        instance=User.objects.create_user(email=email, password=pword, is_customer=True,is_active=False)
        uid = urlsafe_base64_encode(force_bytes(instance.pk)).decode()
        token = account_activation_token.make_token(instance)
        message = 'Please use this link to login http://'+str(current_site)+'/hostel/activate/'+str(uid)+'/'+str(token)+'/'
                    
        send_mail(subject, message, email_from, recipient_list)                    
        return super().form_valid(form)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()        
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.active = True
        user.save()
        login(request, user)
        return HttpResponseRedirect('/hostel/client/')
    else:
        return render(request, 'CRUD/code_verification.html',{'error':'Token is expired'})


def verifyNotification(request):
    return render(request,"CRUD/code_verification.html",{'message1':'Activate Account','message2':'Please confirm your email address to complete registration'})


# class RegisterView(FormView):
#     template_name = "CRUD/RegistrationForm.html"
#     form_class = SignupForm
#     success_url = "/client-login/"

#     def form_valid(self, form):
#         email = form.cleaned_data["email"]
#         pword = form.cleaned_data["password"]
#         User.objects.create_user(email=email, password=pword)
#         return super().form_valid(form)


class Hostel_CreateView(LoginRequiredMixin,UserPassesTestMixin,FormView, SuccessMessageMixin):
    login_url = "/hostel/login/"
    form_class = Hostel_Request_Form

    template_name = "main.html"
    success_url = "/hostel/view/"
    context_object_name = 'form'  # default is object_list
    # def form_valid(self,form):
    #     Hostel_name = form.cleaned_data["Hostel_name"]
    #     Hostel_Address=form.cleaned_data['Hostel_Address']

      
    def test_func(self):                                #fail test only work if returned false
        if self.request.user.is_admin:
            return self.request.user
        return False   
    

class Comments(LoginRequiredMixin,UserPassesTestMixin,ListView):
    login_url = "/hostel/login/"
    model = Hostel_comment 
    template_name = "CRUD/comments.html"
    fields='__all__'
    success_url = "/hostel/comments/"
    context_object_name = 'form'  # default is object_list
    def test_func(self):                                #fail test only work if returned false
        if self.request.user.is_admin:
            return self.request.user
        return False       
    
class Hostel_Comments:
    @login_required(login_url='/hostel/login/')
    def get(request):
        usr=User.objects.get(email=request.user)
        pre=usr.hostel_info_set.all()
        lst=[]
        for e in pre:
            for h in e.hostel_comment_set.all():     
                lst.append(h)
        context={'form':lst,'pre':pre}
        return render(request,'CRUD/ClientHostelComments.html',context)


class Client_CreateView(LoginRequiredMixin,SuccessMessageMixin, FormView,CreateView ):
    login_url="/hostel/login/"
    form_class = Hostel_Request_Form
    template_name = "CRUD/ClientHome.html"
    success_url = "/hostel/client/"
    context_object_name = 'form'  # default is object_list
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES or None)
        files = request.FILES.getlist('image')
        if form.is_valid():
            instance = form.save(commit=False)           
            instance.user_ins = request.user
            lat=request.POST['Hostel_lat']
            lon=request.POST['Hostel_long']
            instance.Hostel_long = lon
            instance.Hostel_lat = lat           
            form.save()
            for f in files:
                try:
                    img=Request_Image.objects.create(Hostel_image=instance,image=f)
                    img.save()
                except:
                    break        
            return HttpResponseRedirect('/hostel/client/')
        return render(request, self.template_name, {'form': form})
    
# def form_valid(self, form):
#         instance=form.save(commit=False)
#         longi=request.POST.get('Hostel_long')
#         lat=request.POST.get('Hostel_lat')
#         print(longi)
#         print(lat)
#         instance.user_ins(self.request.user)
#         instance.Hostel_long(longi)
#         instance.Hostel_lat(lat)
#         instance.save()
#         return super(Hostel_CreateView, self).form_valid(form)

class Hostel_AcceptView:
    
    @user_is_admin_required
    def accept(self, pk):
        pre = Hostel_Request.objects.get(pk=pk)
        instance=Hostel_info.objects.create(user_ins=pre.user_ins, Hostel_name=pre.Hostel_name,
                                    Hostel_Address=pre.Hostel_Address, Hostel_Ph_No=pre.Hostel_Ph_No,
                                    Hostel_Mobile_No=pre.Hostel_Mobile_No, Hostel_Price=pre.Hostel_Price,
                                    Hostel_Estd=pre.Hostel_Estd,Hostel_type=pre.Hostel_type,
                                    Hostel_long=pre.Hostel_long, Hostel_lat=pre.Hostel_lat,
                                    wifi=pre.wifi, lodging=pre.lodging,
                                    studyRoom=pre.studyRoom, medicalFacility=pre.medicalFacility,
                                    singleRoom=pre.singleRoom, dormitory=pre.dormitory,
                                     laundary=pre.laundary,about=pre.about,)            
        pre_img=pre.request_image_set.all()
        for e in pre_img:
            Image.objects.create(Hostel_image=instance,image=e.image)
        Del = Hostel_Request.objects.get(pk=pk)
        Del.delete()
        return HttpResponseRedirect("/hostel/hostel-request-list/")
    @user_is_admin_required
    def requestdetail(self,pk):
        
        form = Hostel_Request.objects.filter(pk=pk)

CRUD/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <title>Base</title>
</head>
{% block css%}
<link rel="stylesheet" href="{% static 'style.css'%}" type="text/css"/>
{% endblock %}
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
                  <a class="navbar-brand" href="{%url 'CRUD:add-hostel' %}">
                    <i class="fas fa-home fa-1x" style="color:blue"></i>
                    Home
                  </a>
                  <a class="navbar-brand" href="{%url 'CRUD:map' %}"><i class="fas fa-map" style="color:blue"></i>
                    Map
                  </a>
                  <a class="navbar-brand" href="{%url 'CRUD:list-hostel' %}">
                    View
                  </a>
                  <div class="d-flex align-items-row">
            <form class="form-inline my-2 my-lg-0" method="POST" action="{%url 'CRUD:search'%}">
              {% csrf_token %}
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="srh">
              <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><i class="fas fa-search fa-1x"></i></button>
              <!--<button class="btn"><i class="fa fa-user"></i></button>-->
            </form>
                    <a class="navbar-brand" style='text-decoration:none'>logged in as {{request.user}}</a>

                    <a class="navbar-brand" href="/manageusers/">Users

                  </a>
                  <a class="navbar-brand" href="/logout/">
                    <i class="fas fa-user fa-1x" style="color:blue"></i>
                    Logout
                  </a>

            </div>
      </div>
      </div>
      </div>

      </nav>
<div class="container">
  <div class="form-group">

    {%if messages%}
    <ul class="messages">
      {%for m in messages%}
        <div class="alert alert-success">{{m}}</div>
      {%endfor%}
      </ul>
    {%endif%}
    </div>
  </div>
{% block body %}
{% endblock %}
</body>
</html>

CRUD/templates/main.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin Area | Dashboard</title>
  <!-- Bootstrap core CSS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  {% endblock %}
  {% block maplinker %}

  {% endblock %}

</head>

<body>

  {% block header %}
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AdminStrap</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{%url 'CRUD:add-hostel'%}">Dashboard</a></li>

          <li> <a id="dmy">2019 Jan 10</a></li>
          <li> <a id="time">12:39:00 PM</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a>Welcome, {{request.user}}</a></li>
          <li><a href="{%url 'CRUD:logout' %}">Logout</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>
  {% endblock %}

  <header id="header">
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          {% block subheader%}
          <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Dashboard <small>Manage Your Site</small>
          </h1>
          {% endblock %}
        </div>
      </div>
    </div>
  </header>


  <section id="breadcrumb">
    <div class="container">
      <ol class="breadcrumb">
        {% block breadcrumbs %}
        <li class="active">Dashboard</li>
        {% endblock %}
      </ol>
    </div>
  </section>
  {% block message%}
  <div class="container">
    <div class="form-group">

      {%if messages%}
      <ul class="messages">
        {%for m in messages%}
        <div class="alert alert-success">{{m}}</div>
        {%endfor%}
      </ul>
      {%endif%}
    </div>
  </div>
  {%endblock%}

  <section id="main">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          {% block sidepanel%}
          <div class="list-group">
            <a href="{%url 'CRUD:add-hostel'%}" class="list-group-item active main-color-bg">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Dashboard
            </a>
            <a href="{%url 'CRUD:list-users'%}" class="list-group-item" style='text-decoration-line: none'><span
                class="glyphicon glyphicon-user" aria-hidden="true"></span> Users <span
                class="badge">{{user_total}}</span></a>
            <a href="{%url 'CRUD:list-hostel'%}" class="list-group-item"><span aria-hidden="true"><i
                  class="far fa-building"></i></span>
              Hostels <span class="badge">{{hostel_total}}</span></a>
            
            <a href="{%url 'CRUD:map'%}" class="list-group-item"><span aria-hidden="true"><i
                  class="fas fa-map"></i></span>
              Map <span class="badge">{{hostel_total}}</span></a>
              
              <a href="{%url 'CRUD:comments'%}" class="list-group-item"><span aria-hidden="true"><i
                class="fas fa-comments"></i></span>
            Comments <span class="badge">{{comment_total}}</span></a>
        
            </div>

        </div>
        {% endblock %}
        <div class="col-md-9">
          <!-- Website Overview -->

          {% block overview %}
          <div class="panel panel-default">
            <div class="panel-heading main-color-bg">
              <h3 class="panel-title">Website Overview</h3>
            </div>
            <div class="panel-body">
              <div class="col-md-3">
                <div class="well dash-box">
                  <h2><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{user_total}}
                  </h2>
                  <a href="{%url 'CRUD:list-users'%}" style='text-decoration: none'>
                    <h3>Users</h3>
                  </a>
                </div>
              </div>

              <div class="col-md-3">
                <div class="well dash-box">
                  <h2><span aria-hidden="true"><i class="far fa-building"></i></span>{{hostel_total}}</h2>
                  <a href="{%url 'CRUD:list-hostel'%}" style='text-decoration: none'>
                    <h3>Hostels</h3>
                  </a>
                </div>
              </div>
              

              <div class="col-md-3">
                <div class="well dash-box">
                  <h2><span aria-hidden="true"><i class="fas fa-map"></i></span>{{hostel_total}}</h2>
              <a href="{%url 'CRUD:map'%}" style='text-decoration: none'>
                <h3>Map</h3>
              </a>
                </div>
              </div>
              
              <div class="col-md-3">
                  <div class="well dash-box">
                    <h2><span aria-hidden="true"><i class="fas fa-comments"></i></span>{{hostel_total}}</h2>
                <a href="{%url 'CRUD:map'%}" style='text-decoration: none'>
                  <h3>Comments</h3>
                </a>
                  </div>
                </div>

              <!-- <div class="col-md-3">
                <div class="well dash-box">
                  <h2><span class="glyphicon glyphicon-stats" aria-hidden="true"></span> 12,334</h2>
                  <h3>Visitors</h3>
                </div>
              </div> -->
            </div>
          </div>
          {% endblock %}

          <!-- Latest Users -->
          {% block body%}
          <div class="panel panel-default">
            <div class="panel-heading main-color-bg">
              <h3 class="panel-title">Latest Users</h3>
            </div>
            <div class="panel-body">
              <table class="table table-striped table-hover">
                <tr>
                  <th>Id</th>
                  <th>Email</th>
                  <th>Joined</th>
                </tr>

                {% for e in latestUser %}
                <tr>
                  {% if e.is_admin == False %}
                  <td>{{ e.id }}</td>
                  <td>{{e.email}}</td>
                  <td>{{e.timestamp}}</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>
  {% endblock %}
  {% block footer%}
  <!-- <footer id="footer">
    <p></p>
  </footer> -->
  {% endblock %}


  <!-- Modals -->
  {% block map%}
  {% endblock%}

  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/datetime.js'%}"></script>
</body>

</html>