Api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views
from .swagger_schema import swagger
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Hostel API')


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'hostel', views.HostelViewSet)
router.register(r'login', views.LoginView, basename='MyModel')
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include(router.urls), name='rest-api'),
    # path('openapi/', TemplateView.as_view(
    #     template_name='CRUD/swagger-ui.html',
    #     extra_context={'schema_url': 'openapi-schema'}
    # ), name='swagger-ui'),
    # path('openapi/', schema_view, name='open-api'),
    path('swagger/', swagger),

    # path('example/', views.ExampleView.as_view()),
    # path('login/', obtain_auth_token, name='api-login'),


]

CRUD/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'CRUD'

urlpatterns = [

    #admin dashboard login,logout...vi
    path('search/', views.Search, name='search'),
    # path('search-user/', views.search, name='search-user'),
    path('map/', views.mapview, name='map'),
    path("login/", LoginView.as_view(), name ='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    #create ,upadte,list and delete single object
    path("main/", Hostel_CreateView.as_view(), name='add-hostel'),
    path('view/', Hostel_ListView.as_view(), name='list-hostel'),
    path('hostel-list/', Hostels.as_view(), name='hostel-list'),
    path('delete/<int:id>/', Hostel_DeleteView.as_view(), name='delete-single-hostel'),
    path('update/<int:id>/', Hostel_UpdateView.as_view(), name='update-hostel'),
    path('manageusers/', Users_ListView.as_view(), name='list-users'),
    
    #path("register/", RegisterView.as_view(),name="register"),
    #list hostel request,accept or delete request
    path('hostel-request-list/', Hostel_Request_ListView.as_view(), name='list-req-hostel'),
    path('hostel-accept/<int:pk>/', Hostel_AcceptView.accept, name='hostel-accept'),
    path('hostel-reject/<int:pk>/', Hostel_RejectView.reject, name='hostel-reject'),
    path('hostel-request-view/<int:pk>', views.hostel_DetailView, name='hostel-request-view'),

    path('delete-hostel/', DeleteGroup.deleteHostel, name='delete-hostel'),
    path('delete-user/', DeleteGroup.deleteUser, name='delete-user'),
    #Client register,create,verify,login
    #path("client-login/", ClientLoginView.as_view()),
    path("register/", ClientRegisterView.as_view(),name="register"),
    path("activation-sent/",views.verifyNotification,name='activation-sent'),
    path("client/", Client_CreateView.as_view(), name='insert'),
    path ("client-map/",views.clientmap,name="client-map"),
    
    
    #url (r"^direction/(?P<h_long>[0-9]+)/$",views.direction,name="direction"),
    path ("direction/<str:h_long>/<str:h_lat>/",views.direction, name='direction'),
    
    path("comments/", Comments.as_view(), name='comments'),
    path("comment-form/<int:id>/",views.commentform,name='commentform'),
    path('delete-comment/', DeleteGroup.deleteComment, name='delete-comment'),
    path('delete-comment-all/', DeleteGroup.deleteCommentAll, name='delete-comment-all'),
    re_path('hostel-comments/', Hostel_Comments.get, name='hostel-comments'),

    #path("user-comment/", views.comment, name='user-comment'),
    
    #sort hostel
    path("cheap-hostel/", views.cheapSortHostel, name='cheap-hostel'),
    path("expen-hostel/", views.expenSortHostel, name='expen-hostel'),
    path("boys-hostel/",views.sortMale, name='boys-hostel'),
    path("girls-hostel/",views.sortFemale, name='girls-hostel'),

    url (r"^search-hostel/$",views.searchhostel),
    path ("hostel-detail/",views.totalhostel,name="total-hostel"),
    #account activaiton link
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    #nearest
    path ("nearest/<str:h_long>/<str:h_lat>/",views.nearest,name="nearest-hostel"),
    
    
]

hostel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from CRUD import views, models
from CRUD.admin import custom_admin_site
from django.views.generic import RedirectView
from rest_framework import routers

#
urlpatterns = [
    path('admin/', custom_admin_site.urls),
    # path('', views.index, name='index'),
    path("hostel/", include("CRUD.urls")),
    path("account/", include("accounts.urls")),
    # path('api-hostel/', views.Api_Hostel.as_view()),
    # path('api-comment/', views.Api_Comment.as_view()),
    # path('api-comment-crud/<int:id>', views.Api_Crud.as_view()),
    # path('api-hostel-add/', views.Api_Hostel_Add.as_view()),
    # path('api-image/', views.Api_Image.as_view()),
    path("", include("Api.urls"))
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

CRUD/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from .models import Hostel_info,Hostel_Request,Request_Image,Image
from .forms import Hostel_Request_Form, Hostel_comment
from django.db.models import Q
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics, serializers
from .serializers import Hostel_infoSerializers, Hostel_commentSerializers,ImageSerializers

from django.contrib.auth.decorators import *
from django.contrib.admin.views.decorators import *
from CRUD.decorators import user_is_admin_required

from django.contrib.auth import get_user_model

from django.views.generic import ListView, DetailView, TemplateView, FormView, View, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .forms import *
from django.contrib.auth import authenticate, login, logout
#send mail
from django.core.mail import send_mail

#Encrypion,decryption,text byte and text
from django.conf import settings
from django.utils.encoding import force_bytes,force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from CRUD.token import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect

User = get_user_model()

def index(request):
    return render(request,"CRUD/index.html")

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/hostel/login/")


class LoginView(FormView):
    template_name = "CRUD/login.html"
    form_class = LoginForm
    redirect_field_name = "/hostel/client-map/" 
    success_url="/hostel/client-map/"          #-------sends to client if not admin

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        user = authenticate(email=email, password=pword)
        if user is not None:
            login(self.request, user)
            if user.is_admin:
                return redirect("/hostel/main/")
        else:
            return render(self.request, "CRUD/login.html", {"error": "Invalid Credential", "form": form})
        return super().form_valid(form)

class ClientLoginView(FormView):
    template_name = "CRUD/login.html"
    form_class = LoginForm
    success_url = "/hostel/client/"
    
    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        user = authenticate(email=email, password=pword)
        if user is not None:
            login(self.request, user)            
        else:
            return render(self.request, "CRUD/login.html", {"error": "Invalid Credential", "form": form})
        return super(ClientLoginView,self).form_valid(form)

      

class ClientRegisterView(FormView):
    template_name = "CRUD/RegistrationForm.html"
    form_class = SignupForm
    success_url = "/hostel/activation-sent/"

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        pword = form.cleaned_data["password"]
        #send message and token for authentication
        subject = 'Thank you for registering to our site'    
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [email,]
        current_site = get_current_site(self.request).domain
        
        instance=User.objects.create_user(email=email, password=pword, is_customer=True,is_active=False)
        uid = urlsafe_base64_encode(force_bytes(instance.pk)).decode()
        token = account_activation_token.make_token(instance)
        message = 'Please use this link to login http://'+str(current_site)+'/hostel/activate/'+str(uid)+'/'+str(token)+'/'
                    
        send_mail(subject, message, email_from, recipient_list)                    
        return super().form_valid(form)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()        
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.active = True
        user.save()
        login(request, user)
        return HttpResponseRedirect('/hostel/client/')
    else:
        return render(request, 'CRUD/code_verification.html',{'error':'Token is expired'})


def verifyNotification(request):
    return render(request,"CRUD/code_verification.html",{'message1':'Activate Account','message2':'Please confirm your email address to complete registration'})


# class RegisterView(FormView):
#     template_name = "CRUD/RegistrationForm.html"
#     form_class = SignupForm
#     success_url = "/client-login/"

#     def form_valid(self, form):
#         email = form.cleaned_data["email"]
#         pword = form.cleaned_data["password"]
#         User.objects.create_user(email=email, password=pword)
#         return super().form_valid(form)


class Hostel_CreateView(LoginRequiredMixin,UserPassesTestMixin,FormView, SuccessMessageMixin):
    login_url = "/hostel/login/"
    form_class = Hostel_Request_Form

    template_name = "main.html"
    success_url = "/hostel/view/"
    context_object_name = 'form'  # default is object_list
    # def form_valid(self,form):
    #     Hostel_name = form.cleaned_data["Hostel_name"]
    #     Hostel_Address=form.cleaned_data['Hostel_Address']

      
    def test_func(self):                                #fail test only work if returned false
        if self.request.user.is_admin:
            return self.request.user
        return False   
    

class Comments(LoginRequiredMixin,UserPassesTestMixin,ListView):
    login_url = "/hostel/login/"
    model = Hostel_comment 
    template_name = "CRUD/comments.html"
    fields='__all__'
    success_url = "/hostel/comments/"
    context_object_name = 'form'  # default is object_list
    def test_func(self):                                #fail test only work if returned false
        if self.request.user.is_admin:
            return self.request.user
        return False       
    
class Hostel_Comments:
    @login_required(login_url='/hostel/login/')
    def get(request):
        usr=User.objects.get(email=request.user)
        pre=usr.hostel_info_set.all()
        lst=[]
        for e in pre:
            for h in e.hostel_comment_set.all():     
                lst.append(h)
        context={'form':lst,'pre':pre}
        return render(request,'CRUD/ClientHostelComments.html',context)


class Client_CreateView(LoginRequiredMixin,SuccessMessageMixin, FormView,CreateView ):
    login_url="/hostel/login/"
    form_class = Hostel_Request_Form
    template_name = "CRUD/ClientHome.html"
    success_url = "/hostel/client/"
    context_object_name = 'form'  # default is object_list
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES or None)
        files = request.FILES.getlist('image')
        if form.is_valid():
            instance = form.save(commit=False)           
            instance.user_ins = request.user
            lat=request.POST['Hostel_lat']
            lon=request.POST['Hostel_long']
            instance.Hostel_long = lon
            instance.Hostel_lat = lat           
            form.save()
            for f in files:
                try:
                    img=Request_Image.objects.create(Hostel_image=instance,image=f)
                    img.save()
                except:
                    break        
            return HttpResponseRedirect('/hostel/client/')
        return render(request, self.template_name, {'form': form})
    
# def form_valid(self, form):
#         instance=form.save(commit=False)
#         longi=request.POST.get('Hostel_long')
#         lat=request.POST.get('Hostel_lat')
#         print(longi)
#         print(lat)
#         instance.user_ins(self.request.user)
#         instance.Hostel_long(longi)
#         instance.Hostel_lat(lat)
#         instance.save()
#         return super(Hostel_CreateView, self).form_valid(form)

class Hostel_AcceptView:
    
    @user_is_admin_required
    def accept(self, pk):
        pre = Hostel_Request.objects.get(pk=pk)
        instance=Hostel_info.objects.create(user_ins=pre.user_ins, Hostel_name=pre.Hostel_name,
                                    Hostel_Address=pre.Hostel_Address, Hostel_Ph_No=pre.Hostel_Ph_No,
                                    Hostel_Mobile_No=pre.Hostel_Mobile_No, Hostel_Price=pre.Hostel_Price,
                                    Hostel_Estd=pre.Hostel_Estd,Hostel_type=pre.Hostel_type,
                                    Hostel_long=pre.Hostel_long, Hostel_lat=pre.Hostel_lat,
                                    wifi=pre.wifi, lodging=pre.lodging,
                                    studyRoom=pre.studyRoom, medicalFacility=pre.medicalFacility,
                                    singleRoom=pre.singleRoom, dormitory=pre.dormitory,
                                     laundary=pre.laundary,about=pre.about,)            
        pre_img=pre.request_image_set.all()
        for e in pre_img:
            Image.objects.create(Hostel_image=instance,image=e.image)
        Del = Hostel_Request.objects.get(pk=pk)
        Del.delete()
        return HttpResponseRedirect("/hostel/hostel-request-list/")
    @user_is_admin_required
    def requestdetail(self,pk):
        
        form = Hostel_Request.objects.filter(pk=pk)

CRUD/templates/CRUD/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css"
    />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
      const ui = SwaggerUIBundle({
        url: "{% url 'CRUD:login' %}",
        dom_id: "#swagger-ui",
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout"
      });
    </script>
  </body>
</html>

CRUD/templates/CRUD/totalhostel.html

{% load static %}
{% load hostel_tags%}
{% load crispy_forms_tags %}

 
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


	
	
</head>


<body>
	<nav class="navbar navbar-expand-lg " style="background-color: #e74c3c;">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
    	<li class="nav-item ">
        <a href="{% url 'CRUD:client-map' %}"class="nav-link">Home </a>
      </li>
      <!-- <li class="nav-item ">
        <a class="nav-link" id="dmy" href="#">2019 Jan 10 </a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  id="time" href="#">12:39:00 PM</a>
      </li> -->
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort hostel by
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'CRUD:boys-hostel'%}">Male</a>
          <a class="dropdown-item" href="{% url 'CRUD:girls-hostel'%}">Female</a>
          
          <a class="dropdown-item" href="{% url 'CRUD:expen-hostel'%}">Expensive Hostel</a>
          <a class="dropdown-item" href="{% url 'CRUD:cheap-hostel'%}">Cheapest Hostel</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<style>
 		.row{
 			justify-content: center;
			align-items: center;
 		}
 		/*#next-button{
 			background-color:black; 		
 		}*/
 		a{
 			color:white;
 		}
 		
 		body{
 			overflow-x: hidden;
 			overflow-y: scroll;
 			 		}
 		.custom-button{
			display:inline-block;
		/**other codes**/
		}
		.card-img-top {
    		width: 100%;
    		height: 15vw;
    		object-fit: cover;
		}
		/*.button-review {
  background-color: #555555; /* Green */
  /*border: none;*
  color: white;
  padding: 7px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;*/
}
		
		
		
		
</style>




<!-- <-------------------------------------------body	 -->
	<div class="container">
        <div class="row">
	{% for h in h %}
        <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
                <div class="card " style="width:15rem;height:27rem">
                	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
						<div class="carousel-inner">
							
							   {% set 1 as a %}
							   	{% for e in e %}
							   	{% ifequal h.id e.Hostel_image.id %}
							   	{% if a == 1%}							   
							   	{% set 2 as a%}
							   	<div class="carousel-item active">
							      <img class="card-img-top" src="{{e.image.url}}" alt="{{counter}}">
							    <!-- <h1>{{h.Hostel_image}}</h1> -->							   	
							    </div>
							    {% else %}							    
							    <div class="carousel-item ">
							      <img class="card-img-top" src="{{e.image.url}}"  >
							    </div>
							    {% endif %}
							    {% endifequal %}
							   	{% endfor %}
						
							    
						</div>
						<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
						    <span class="carousel-control-prev-icon" ></span>
						    <span class="sr-only">Previous</span>
						 </a>
						 <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
						    <span id="next-button" class="carousel-control-next-icon" ></span>
						    <span class="sr-only">Next</span>
						 </a>
  					</div>
                    <div class="card-body">
                        <h5 class="text-bold">{{h.Hostel_name}}</h5>
                        <p class="card-text">Type: {{h.Hostel_type}}
                        <br/>Cost Price: {% if h.Hostel_Price %}(Rs){{h.Hostel_Price}}{% else %}Negotiable
                        {% endif %}
                        <br/>
                    	Contact: {% if h.Hostel_Ph_No %}{{h.Hostel_Ph_No}},{% endif %}
                    {% if h.Hostel_Mobile_No %}{{h.Hostel_Mobile_No}}{% endif %}</p>
                    	<div class="modal-footer">
  					<a  class="btn btn-outline-primary my-2 my-sm-0" href="{% url 'CRUD:direction' h_long=h.Hostel_long h_lat=h.Hostel_lat %}">Direction</a></p>
                        <!-- <a id="button1" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                        href="#">Review</a> -->
                        <a  href="{% url 'CRUD:commentform' h.id %}"user="{{request.user}}" h-id="{{h.id}}"  class="btn btn-outline-primary my-2 my-sm-0"  data-target="#exampleModal">
                        	Detail
                        </a>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
		<div>
	</div>
	
 <!-- {% for e in e %}
 {% for h in h %}
 {% ifequal h.id e.Hostel_image.id %}
 <h1>yes</h1>
 {% endifequal %}
 
 {% endfor %}

 
 {% endfor %} -->
 	<!-- <div class="bg-modal">
 		<div class="modal-content">
 		
 		</div>
 	</div> -->
 	
	<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Post Comment</h5>
       

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
        
      </div>
      <div class="modal-body" >
      <div class="modal-form">
      						<form id="post-comment" action="."class="form-horizontal">
							{% csrf_token %}
                              <div class="form-group">
                              <textarea  class = "form-control" id='areaforinfo' style="min-width: 100%"></textarea>      
                          </div>
 <button  type="submit"  class="post-comment">Post</button>      	
        </form>
    </div>
    <!-- {% for each in nonjson %} -->
        <div class="modal-comment">
        	<blockquote  class="blockquote text-right">
			  <p class="mb-0" id="block-quote"></p>
			  <footer class="blockquote-footer"> <cite id="comment-by" title="Source Title"></cite></footer>
			</blockquote>
      </div>
    <!-- {% endfor %}   --> 
      </div>

      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       
      </div> -->
    </div>tei
  </div>
</div>
	<script>
		 $('.button-review').click(function(){
			console.log("yes");
			var id;
			id=$(this).attr("h-id");
			console.log("id="+id);
			$.ajax(
			{
				type:"GET",
				url:"/user-comment/",
				dataType:'json',
				data:{
					hostel_id:id
				},
				success:function(data){
					
					var comments=JSON.parse(data.comments)
					var htmlTag='';
					comments.forEach(comment=>{
						htmlTag+='<blockquote id="block-quote" class="blockquote text-right"><p class="mb-1">'+comment.fields.comment+'</p>';
						htmlTag+='<footer class="blockquote-footer">'+"by "+'<cite title="Source Title">'+comment.fields.email+'</cite></footer>';
						htmlTag+="</blockquote>";
					});
					// 		comments.forEach(comment=>{
					// 	console.log($('#block-quote').text(comment.fields.comment))
					// 		// $('#block-quote').text($(request.user);
					// });

					// $(".modal-comment").append(htmlTag);
				
					$(window).unload(function() {
   console.log("closed");
});

				}
				
				
			})

		});
        $('#post-comment').on('submit', function(event){
        	event.preventDefault();
        	console.log($('#areaforinfo').val())
			//console.log("yes");
			var comment;
			comment=($('#areaforinfo').val())
			var id,email;
			id=document.getElementById("button2").getAttribute("h-id");
			console.log(id)
			email=document.getElementById("button2").getAttribute("user");
			console.log(email);
			$.ajaxSetup({ 
			     beforeSend: function(xhr, settings) {

			         function getCookie(name) {
			             var cookieValue = null;
			             if (document.cookie && document.cookie != '') {
			                 var cookies = document.cookie.split(';');
			                 for (var i = 0; i < cookies.length; i++) {
			                     var cookie = jQuery.trim(cookies[i]);
			                     // Does this cookie string begin with the name we want?
			                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
			                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
			                         break;
			                     }
			                 }
			             }
			             return cookieValue;
			         }
			         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
			             // Only send the token to relative URLs i.e. locally.
			             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
			         }
			     } 
			});
			
			$.ajax(
			{
				type:"POST",
				url:"/user-comment/",
				dataType:'json',
				data:{
					hostel_comment:comment,
					hostel_id:id,
					email:email
				},
				success:function(data){

					
					var comments=JSON.parse(data.comments)
					var htmlTag='';
					comments.forEach(comment=>{
						htmlTag+='<blockquote class="blockquote text-right"><p class="mb-1">'+comment.fields.comment+'</p>';
						htmlTag+='<footer class="blockquote-footer">'+"by "+'<cite id="commrnt-by" title="Source Title">'+comment.fields.email+'</cite></footer>';
						htmlTag+="</blockquote>";
					});
					// comments.forEach(comment=>{
					// 	$('#block-quote').text(comment);
					// 		// $('#block-quote').text($(request.user);
					// });

					
					
					 $(".modal-comment").append(htmlTag);
					// location.reload(true);
				},
				error:function(rs,e){
					console.log(rs.responseText);
				},
				
			})

		});



	</script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/datetime.js'%}"></script>
	
</body>
</html>